### ISSUE TITLE
callisto::graphics opengl change logic

### ISSUE THREAD

**Issue by CherryMan23** [CherryMan23/callisto#3]
- [x] create new class **gl_uniform_location** which store location id and move all uniform* methods from **gl_shader_program** into it.
- [x] Added method **is_exist** to **gl_uniform_location** which cheked GLint uniform location value to not equal -1 (Uniform not exist).
- [x] change logic of **get_uniform location** method. It Should return gl_unfiform_location class instead of GLInt.
- [x] add check and exception throwing logic in method get_uniform_location.
- [x] add nothrow logic **get_uniform_location_nothrow** with old logic (returning uniform location).
- [x] add uniform methods for callisto::math data.
- [x] add **GLuint/GLint  get_handler() const** methods to all wraping class when these methods are not exist.

**Comment by Anton-Vasyaev** [comment]
Done, commit: b924f7aa4dbe6da0288718b5cf6a24124b43902d

**Comment by CherryMan23** [comment]
Done, commit: 715d38049fb22444ee1b2f6605c3d4c346d77ab1
